### PR TITLE
Remove Event, RoomEvent, StateEvent traits  and related macros + codegen

### PR DESCRIPTION
**Pull request by DevinR528**
Starts work on #82

### CODE REVIEW

**Comment by jplatte** [comment]
Thanks for working on this! :)

Here's the next steps that I think should probably each be in their own commit:

* Remove the `Event` types, leaving only `EventContent` types
* Add one of the proposed generic event types, for example `StateEvent`, and its corresponding collection type `AnyStateEvent` (a separate private module `state` for this with re-exports at the crate root would probably be a good idea). I think the collection `Deserialize` and `Serialize` can actually be derived, but in a not-so-optimal fashion: We will have to re-declare the "type" string for every collection. Also, it would be nice to have `StateEvent<Something>`'s serialized form also include the type field (which I think isn't currently the case for `ToDevice<Something>` and `Stripped<Something>`).

**Comment by DevinR528** [comment]
Just to clarify "`Event` types" are anything inside of the `Event/RoomEvent/StateEvent` enums, removing the generated `Event` types also? Then in the next commit replace them with the proposed generic types, we'll start with `StateEvent` to see how it goes.

**Comment by jplatte** [comment]
Yes, exactly. Though maybe it would be better to comment out the `collections` module for now instead of deleting it altogether.

**Comment by jplatte** [comment]
I've just set up a new branch, `api22`, to hold the new API as long as it's still incomplete. Could you please open another PR against that branch with the same changes you've already done except

1. not as a WIP PR
2. without removing `fn to_camel_case` and the `kind` field on `RumaEvent` in the macro crate
   * we're going to need the former for other codegen later
   * we're going to need the latter for [this](https://github.com/ruma/ruma-events/issues/82#issuecomment-624206044)

Thanks!

**Pull request closed without merging**
